# Generated by Django 5.2.12 on 2026-03-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate_app", "0002_property_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Live", "Live"),
                    ("Booked", "Booked"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
